[package]
name = "ai-writer"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
dotenvy = "0.15.7"
edit = "0.1.5"
log = "0.4.21"
log4rs = "1.3.0"
openai = "1.0.0-alpha.14"
tokio = "1.38.0"
